println("Welcome to the tip calculator!")
print("What was the total bill? \$")
bill = parse(Float64, readline())
print("How much tip would you like to give? 10%, 12%, or 15%? ")
tip = parse(Float64, readline())
print("How many people to split the bill? ")
people = parse(Int64, readline())
pay = round(bill * (1 + tip / 100) / people, digits=2)
println("Each person should pay: \$$pay")
