println("Welcome to the Band Name Generator.")
println("What's name of the city you grew up in?")
city = readline()
println("What's your pet's name?")
pet = readline()
println("Your band name could be $city $pet")
